const items = [
    
    {
        id: 1,
        item_img: "./imgs/osTshirt/1.webp",
        item_name: "Oversized T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 2,
        item_img: "./imgs/osTshirt/2.webp",
        item_name: "Oversized SUPIMA T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 3,
        item_img: "./imgs/osTshirt/3.webp",
        item_name: "Oversized Fabric T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 4,
        item_img: "./imgs/osTshirt/4.webp",
        item_name: "Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 5,
        item_img: "./imgs/poloTshirt/1.webp",
        item_name: "Oversized Polo T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 6,
        item_img: "./imgs/poloTshirt/2.webp",
        item_name: "Polo T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 7,
        item_img: "./imgs/poloTshirt/3.webp",
        item_name: "Fabric Polo T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 8,
        item_img: "./imgs/poloTshirt/4.webp",
        item_name: "Polo Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 9,
        item_img: "./imgs/cropTop/1.webp",
        item_name: "Fit Navy Blue Pique Top",
        price: 799,
    },
    {
        id: 10,
        item_img: "./imgs/cropTop/2.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1899,
    },
    {
        id: 11,
        item_img: "./imgs/cropTop/3.webp",
        item_name: "Oversized Top - Be The Change",
        price: 1099,
    },
    {
        id: 12,
        item_img: "./imgs/cropTop/4.webp",
        item_name: "Oversized SUPIMA Top",
        price: 999,
    },
    {
        id: 13,
        item_img: "./imgs/cropTop/5.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1199,
    },
    {
        id: 14,
        item_img: "./imgs/cropTop/6.webp",
        item_name: "Textured Regular Pique Top",
        price: 1399,
    },
    {
        id: 15,
        item_img: "./imgs/cropTop/7.webp",
        item_name: "Regular Fit Pique Top",
        price: 899,
    },
    {
        id: 16,
        item_img: "./imgs/hoodies/1.webp",
        item_name: "Oversized SUPIMA Hoodie - Be The Change",
        price: 1199,
    },
    {
        id: 17,
        item_img: "./imgs/hoodies/2.webp",
        item_name: "SUPIMA Hoodie - Be The Change",
        price: 1899,
    },
    {
        id: 18,
        item_img: "./imgs/hoodies/3.webp",
        item_name: "Oversized Hoodie - Be The Change",
        price: 1399,
    },
    {
        id: 19,
        item_img: "./imgs/hoodies/4.webp",
        item_name: "Oversized SUPIMA Hoodie",
        price: 1599,
    },
    {
        id: 20,
        item_img: "./imgs/bottoms2/1.webp",
        item_name: "Fit Navy Blue Pique Bottom",
        price: 1199,
    },
    {
        id: 21,
        item_img: "./imgs/bottoms2/2.webp",
        item_name: "SUPIMA Bottom - Be The Change",
        price: 1299,
    },
    {
        id: 22,
        item_img: "./imgs/sweatshirt2/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 23,
        item_img: "./imgs/sweatshirt2/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 24,
        item_img: "./imgs/sweatshirt2/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 25,
        item_img: "./imgs/sweatshirt2/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 26,
        item_img: "./imgs/sweatshirt2/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 27,
        item_img: "./imgs/sweatshirt2/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 28,
        item_img: "./imgs/sweatshirt2/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 29,
        item_img: "./imgs/sweatshirt2/1.webp",
        item_name: "Fit Navy Blue Pique Sweatshirt",
        price: 799,
    },
    {
        id: 30,
        item_img: "./imgs/tshirt/1.webp",
        item_name: "Oversized SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 31,
        item_img: "./imgs/tshirt/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 32,
        item_img: "./imgs/tshirt/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 33,
        item_img: "./imgs/tshirt/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 34,
        item_img: "./imgs/tshirt/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 35,
        item_img: "./imgs/tshirt/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 36,
        item_img: "./imgs/tshirt/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 1299,
    },
    {
        id: 37,
        item_img: "./imgs/tshirt/8.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 999,
    },
    {
        id: 38,
        item_img: "./imgs/tshirt/9.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 39,
        item_img: "./imgs/tshirt/10.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1099,
    },
    {
        id: 40,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1199,
    },
    {
        id: 41,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 42,
        item_img: "./imgs/bottoms1/1.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 43,
        item_img: "./imgs/bottoms1/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 44,
        item_img: "./imgs/bottoms1/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 45,
        item_img: "./imgs/bottoms1/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 46,
        item_img: "./imgs/bottoms1/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 47,
        item_img: "./imgs/bottoms1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 48,
        item_img: "./imgs/bottoms1/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 899,
    },
    {
        id: 49,
        item_img: "./imgs/sweatshirt1/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 50,
        item_img: "./imgs/sweatshirt1/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 51,
        item_img: "./imgs/sweatshirt1/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 52,
        item_img: "./imgs/sweatshirt1/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 53,
        item_img: "./imgs/sweatshirt1/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 54,
        item_img: "./imgs/sweatshirt1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 55,
        item_img: "./imgs/sweatshirt1/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 56,
        item_img: "./imgs/sweatshirt1/8.webp",
        item_name: "Fit Navy Blue Pique Sweatshirt",
        price: 799,
    },
    {
        id: 57,
        item_img: "./imgs/tshirt/1.webp",
        item_name: "Oversized SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 58,
        item_img: "./imgs/tshirt/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 59,
        item_img: "./imgs/tshirt/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 60,
        item_img: "./imgs/tshirt/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 61,
        item_img: "./imgs/tshirt/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 62,
        item_img: "./imgs/tshirt/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 63,
        item_img: "./imgs/tshirt/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 899,
    },
    {
        id: 64,
        item_img: "./imgs/tshirt/8.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 65,
        item_img: "./imgs/bottoms1/1.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 66,
        item_img: "./imgs/bottoms1/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 67,
        item_img: "./imgs/bottoms1/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 68,
        item_img: "./imgs/bottoms1/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 69,
        item_img: "./imgs/bottoms1/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 70,
        item_img: "./imgs/bottoms1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 71,
        item_img: "./imgs/bottoms1/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 899,
    },
    {
        id: 72,
        item_img: "./imgs/bottoms2/1.webp",
        item_name: "Fit Navy Blue Pique Bottom",
        price: 1199,
    },
    {
        id: 73,
        item_img: "./imgs/bottoms2/2.webp",
        item_name: "SUPIMA Bottom - Be The Change",
        price: 1299,
    },
    {
        id: 74,
        item_img: "./imgs/cropTop/1.webp",
        item_name: "Fit Navy Blue Pique Top",
        price: 799,
    },
    {
        id: 75,
        item_img: "./imgs/cropTop/2.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1899,
    },
    {
        id: 76,
        item_img: "./imgs/cropTop/3.webp",
        item_name: "Oversized Top - Be The Change",
        price: 1099,
    },
    {
        id: 77,
        item_img: "./imgs/cropTop/4.webp",
        item_name: "Oversized SUPIMA Top",
        price: 999,
    },
    {
        id: 78,
        item_img: "./imgs/cropTop/5.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1199,
    },
    {
        id: 79,
        item_img: "./imgs/cropTop/6.webp",
        item_name: "Textured Regular Pique Top",
        price: 1399,
    },
    {
        id: 80,
        item_img: "./imgs/cropTop/7.webp",
        item_name: "Regular Fit Pique Top",
        price: 899,
    },
    {
        id: 81,
        item_img: "./imgs/hoodies/1.webp",
        item_name: "Oversized SUPIMA Hoodie - Be The Change",
        price: 1199,
    },
    {
        id: 82,
        item_img: "./imgs/hoodies/2.webp",
        item_name: "SUPIMA Hoodie - Be The Change",
        price: 1899,
    },
    {
        id: 83,
        item_img: "./imgs/hoodies/3.webp",
        item_name: "Oversized Hoodie - Be The Change",
        price: 1399,
    },
    {
        id: 84,
        item_img: "./imgs/hoodies/4.webp",
        item_name: "Oversized SUPIMA Hoodie",
        price: 1599,
    },
    {
        id: 85,
        item_img: "./imgs/osTshirt/1.webp",
        item_name: "Oversized T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 86,
        item_img: "./imgs/osTshirt/2.webp",
        item_name: "Oversized SUPIMA T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 87,
        item_img: "./imgs/osTshirt/3.webp",
        item_name: "Oversized Fabric T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 88,
        item_img: "./imgs/osTshirt/4.webp",
        item_name: "Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 89,
        item_img: "./imgs/poloTshirt/1.webp",
        item_name: "Oversized Polo T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 90,
        item_img: "./imgs/poloTshirt/2.webp",
        item_name: "Polo T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 91,
        item_img: "./imgs/poloTshirt/3.webp",
        item_name: "Fabric Polo T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 92,
        item_img: "./imgs/poloTshirt/4.webp",
        item_name: "Polo Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 93,
        item_img: "./imgs/sweatshirt1/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 94,
        item_img: "./imgs/sweatshirt1/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 95,
        item_img: "./imgs/sweatshirt1/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 96,
        item_img: "./imgs/sweatshirt1/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 97,
        item_img: "./imgs/sweatshirt1/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 98,
        item_img: "./imgs/sweatshirt1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 99,
        item_img: "./imgs/sweatshirt1/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 100,
        item_img: "./imgs/sweatshirt1/8.webp",
        item_name: "Fit Navy Blue Pique Sweatshirt",
        price: 799,
    },
    {
        id: 101,
        item_img: "./imgs/sweatshirt2/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 102,
        item_img: "./imgs/sweatshirt2/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 103,
        item_img: "./imgs/sweatshirt2/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 104,
        item_img: "./imgs/sweatshirt2/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 105,
        item_img: "./imgs/sweatshirt2/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 106,
        item_img: "./imgs/sweatshirt2/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 107,
        item_img: "./imgs/sweatshirt2/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 108,
        item_img: "./imgs/tshirt/1.webp",
        item_name: "Oversized SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 109,
        item_img: "./imgs/tshirt/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 110,
        item_img: "./imgs/tshirt/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 111,
        item_img: "./imgs/tshirt/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 112,
        item_img: "./imgs/tshirt/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 113,
        item_img: "./imgs/tshirt/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 114,
        item_img: "./imgs/tshirt/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 1299,
    },
    {
        id: 115,
        item_img: "./imgs/tshirt/8.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 999,
    },
    {
        id: 116,
        item_img: "./imgs/tshirt/9.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 117,
        item_img: "./imgs/tshirt/10.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1099,
    },
    {
        id: 118,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1199,
    },
    {
        id: 119,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1399,
    }
]

const shopAll = [
    {
        id: 1,
        item_img: "./imgs/osTshirt/1.webp",
        item_name: "Oversized T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 2,
        item_img: "./imgs/osTshirt/2.webp",
        item_name: "Oversized SUPIMA T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 3,
        item_img: "./imgs/osTshirt/3.webp",
        item_name: "Oversized Fabric T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 4,
        item_img: "./imgs/osTshirt/4.webp",
        item_name: "Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 5,
        item_img: "./imgs/poloTshirt/1.webp",
        item_name: "Oversized Polo T-Shirt - Be The Change",
        price: 1199,
    },
    {
        id: 6,
        item_img: "./imgs/poloTshirt/2.webp",
        item_name: "Polo T-Shirt - Be The Change",
        price: 1899,
    },
    {
        id: 7,
        item_img: "./imgs/poloTshirt/3.webp",
        item_name: "Fabric Polo T-Shirt - Be The Change",
        price: 1399,
    },
    {
        id: 8,
        item_img: "./imgs/poloTshirt/4.webp",
        item_name: "Polo Oversized SUPIMA T-Shirt",
        price: 1599,
    },
    {
        id: 9,
        item_img: "./imgs/cropTop/1.webp",
        item_name: "Fit Navy Blue Pique Top",
        price: 799,
    },
    {
        id: 10,
        item_img: "./imgs/cropTop/2.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1899,
    },
    {
        id: 11,
        item_img: "./imgs/cropTop/3.webp",
        item_name: "Oversized Top - Be The Change",
        price: 1099,
    },
    {
        id: 12,
        item_img: "./imgs/cropTop/4.webp",
        item_name: "Oversized SUPIMA Top",
        price: 999,
    },
    {
        id: 13,
        item_img: "./imgs/cropTop/5.webp",
        item_name: "SUPIMA Top - Be The Change",
        price: 1199,
    },
    {
        id: 14,
        item_img: "./imgs/cropTop/6.webp",
        item_name: "Textured Regular Pique Top",
        price: 1399,
    },
    {
        id: 15,
        item_img: "./imgs/cropTop/7.webp",
        item_name: "Regular Fit Pique Top",
        price: 899,
    },
    {
        id: 16,
        item_img: "./imgs/hoodies/1.webp",
        item_name: "Oversized SUPIMA Hoodie - Be The Change",
        price: 1199,
    },
    {
        id: 17,
        item_img: "./imgs/hoodies/2.webp",
        item_name: "SUPIMA Hoodie - Be The Change",
        price: 1899,
    },
    {
        id: 18,
        item_img: "./imgs/hoodies/3.webp",
        item_name: "Oversized Hoodie - Be The Change",
        price: 1399,
    },
    {
        id: 19,
        item_img: "./imgs/hoodies/4.webp",
        item_name: "Oversized SUPIMA Hoodie",
        price: 1599,
    },
    {
        id: 20,
        item_img: "./imgs/bottoms2/1.webp",
        item_name: "Fit Navy Blue Pique Bottom",
        price: 1199,
    },
    {
        id: 21,
        item_img: "./imgs/bottoms2/2.webp",
        item_name: "SUPIMA Bottom - Be The Change",
        price: 1299,
    },
    {
        id: 22,
        item_img: "./imgs/sweatshirt2/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 23,
        item_img: "./imgs/sweatshirt2/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 24,
        item_img: "./imgs/sweatshirt2/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 25,
        item_img: "./imgs/sweatshirt2/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 26,
        item_img: "./imgs/sweatshirt2/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 27,
        item_img: "./imgs/sweatshirt2/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 28,
        item_img: "./imgs/sweatshirt2/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 29,
        item_img: "./imgs/sweatshirt2/1.webp",
        item_name: "Fit Navy Blue Pique Sweatshirt",
        price: 799,
    },
    {
        id: 30,
        item_img: "./imgs/tshirt/1.webp",
        item_name: "Oversized SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 31,
        item_img: "./imgs/tshirt/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 32,
        item_img: "./imgs/tshirt/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 33,
        item_img: "./imgs/tshirt/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 34,
        item_img: "./imgs/tshirt/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 35,
        item_img: "./imgs/tshirt/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 36,
        item_img: "./imgs/tshirt/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 1299,
    },
    {
        id: 37,
        item_img: "./imgs/tshirt/8.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 999,
    },
    {
        id: 38,
        item_img: "./imgs/tshirt/9.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 39,
        item_img: "./imgs/tshirt/10.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1099,
    },
    {
        id: 40,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1199,
    },
    {
        id: 41,
        item_img: "./imgs/tshirt/12.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 42,
        item_img: "./imgs/bottoms1/1.webp",
        item_name: "Fit Navy Blue Pique T-shirt",
        price: 799,
    },
    {
        id: 43,
        item_img: "./imgs/bottoms1/2.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1899,
    },
    {
        id: 44,
        item_img: "./imgs/bottoms1/3.webp",
        item_name: "Oversized T-shirt - Be The Change",
        price: 1099,
    },
    {
        id: 45,
        item_img: "./imgs/bottoms1/4.webp",
        item_name: "Oversized SUPIMA T-shirt",
        price: 999,
    },
    {
        id: 46,
        item_img: "./imgs/bottoms1/5.webp",
        item_name: "SUPIMA T-shirt - Be The Change",
        price: 1199,
    },
    {
        id: 47,
        item_img: "./imgs/bottoms1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
        price: 1399,
    },
    {
        id: 48,
        item_img: "./imgs/bottoms1/7.webp",
        item_name: "Regular Fit Navy Blue Pique T-shirt",
        price: 899,
    },
    {
        id: 49,
        item_img: "./imgs/sweatshirt1/1.webp",
        item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 50,
        item_img: "./imgs/sweatshirt1/2.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1899,
    },
    {
        id: 51,
        item_img: "./imgs/sweatshirt1/3.webp",
        item_name: "Oversized Sweatshirt - Be The Change",
        price: 1099,
    },
    {
        id: 52,
        item_img: "./imgs/sweatshirt1/4.webp",
        item_name: "Oversized SUPIMA Sweatshirt",
        price: 999,
    },
    {
        id: 53,
        item_img: "./imgs/sweatshirt1/5.webp",
        item_name: "SUPIMA Sweatshirt - Be The Change",
        price: 1199,
    },
    {
        id: 54,
        item_img: "./imgs/sweatshirt1/6.webp",
        item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
        price: 1399,
    },
    {
        id: 55,
        item_img: "./imgs/sweatshirt1/7.webp",
        item_name: "Regular Fit Navy Blue Pique Sweatshirt",
        price: 899,
    },
    {
        id: 56,
        item_img: "./imgs/sweatshirt1/8.webp",
        item_name: "Fit Navy Blue Pique Sweatshirt",
        price: 799,
    }
] 

const heroImgs = [{
    id: 57,
    item_img: "./imgs/tshirt/1.webp",
    item_name: "Oversized SUPIMA T-shirt - Be The Change",
    price: 1199,
},
{
    id: 58,
    item_img: "./imgs/tshirt/2.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1899,
},
{
    id: 59,
    item_img: "./imgs/tshirt/3.webp",
    item_name: "Oversized T-shirt - Be The Change",
    price: 1099,
},
{
    id: 60,
    item_img: "./imgs/tshirt/4.webp",
    item_name: "Oversized SUPIMA T-shirt",
    price: 999,
},
{
    id: 61,
    item_img: "./imgs/tshirt/5.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1199,
},
{
    id: 62,
    item_img: "./imgs/tshirt/6.webp",
    item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
    price: 1399,
},
{
    id: 63,
    item_img: "./imgs/tshirt/7.webp",
    item_name: "Regular Fit Navy Blue Pique T-shirt",
    price: 899,
},
{
    id: 64,
    item_img: "./imgs/tshirt/8.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 799,
}]

const maleBottoms = [{
    id: 65,
    item_img: "./imgs/bottoms1/1.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 799,
},
{
    id: 66,
    item_img: "./imgs/bottoms1/2.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1899,
},
{
    id: 67,
    item_img: "./imgs/bottoms1/3.webp",
    item_name: "Oversized T-shirt - Be The Change",
    price: 1099,
},
{
    id: 68,
    item_img: "./imgs/bottoms1/4.webp",
    item_name: "Oversized SUPIMA T-shirt",
    price: 999,
},
{
    id: 69,
    item_img: "./imgs/bottoms1/5.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1199,
},
{
    id: 70,
    item_img: "./imgs/bottoms1/6.webp",
    item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
    price: 1399,
},
{
    id: 71,
    item_img: "./imgs/bottoms1/7.webp",
    item_name: "Regular Fit Navy Blue Pique T-shirt",
    price: 899,
}]

const femaleBottoms = [{
    id: 72,
    item_img: "./imgs/bottoms2/1.webp",
    item_name: "Fit Navy Blue Pique Bottom",
    price: 1199,
},
{
    id: 73,
    item_img: "./imgs/bottoms2/2.webp",
    item_name: "SUPIMA Bottom - Be The Change",
    price: 1299,
}]

const cropTops = [{
    id: 74,
    item_img: "./imgs/cropTop/1.webp",
    item_name: "Fit Navy Blue Pique Top",
    price: 799,
},
{
    id: 75,
    item_img: "./imgs/cropTop/2.webp",
    item_name: "SUPIMA Top - Be The Change",
    price: 1899,
},
{
    id: 76,
    item_img: "./imgs/cropTop/3.webp",
    item_name: "Oversized Top - Be The Change",
    price: 1099,
},
{
    id: 77,
    item_img: "./imgs/cropTop/4.webp",
    item_name: "Oversized SUPIMA Top",
    price: 999,
},
{
    id: 78,
    item_img: "./imgs/cropTop/5.webp",
    item_name: "SUPIMA Top - Be The Change",
    price: 1199,
},
{
    id: 79,
    item_img: "./imgs/cropTop/6.webp",
    item_name: "Textured Regular Pique Top",
    price: 1399,
},
{
    id: 80,
    item_img: "./imgs/cropTop/7.webp",
    item_name: "Regular Fit Pique Top",
    price: 899,
}]

const hoodies = [{
    id: 81,
    item_img: "./imgs/hoodies/1.webp",
    item_name: "Oversized SUPIMA Hoodie - Be The Change",
    price: 1199,
},
{
    id: 82,
    item_img: "./imgs/hoodies/2.webp",
    item_name: "SUPIMA Hoodie - Be The Change",
    price: 1899,
},
{
    id: 83,
    item_img: "./imgs/hoodies/3.webp",
    item_name: "Oversized Hoodie - Be The Change",
    price: 1399,
},
{
    id: 84,
    item_img: "./imgs/hoodies/4.webp",
    item_name: "Oversized SUPIMA Hoodie",
    price: 1599,
}]

const osTshirts = [{
    id: 85,
    item_img: "./imgs/osTshirt/1.webp",
    item_name: "Oversized T-Shirt - Be The Change",
    price: 1199,
},
{
    id: 86,
    item_img: "./imgs/osTshirt/2.webp",
    item_name: "Oversized SUPIMA T-Shirt - Be The Change",
    price: 1899,
},
{
    id: 87,
    item_img: "./imgs/osTshirt/3.webp",
    item_name: "Oversized Fabric T-Shirt - Be The Change",
    price: 1399,
},
{
    id: 88,
    item_img: "./imgs/osTshirt/4.webp",
    item_name: "Oversized SUPIMA T-Shirt",
    price: 1599,
}]

const poloTshirts = [{
    id: 89,
    item_img: "./imgs/poloTshirt/1.webp",
    item_name: "Oversized Polo T-Shirt - Be The Change",
    price: 1199,
},
{
    id: 90,
    item_img: "./imgs/poloTshirt/2.webp",
    item_name: "Polo T-Shirt - Be The Change",
    price: 1899,
},
{
    id: 91,
    item_img: "./imgs/poloTshirt/3.webp",
    item_name: "Fabric Polo T-Shirt - Be The Change",
    price: 1399,
},
{
    id: 92,
    item_img: "./imgs/poloTshirt/4.webp",
    item_name: "Polo Oversized SUPIMA T-Shirt",
    price: 1599,
}]

const maleSweatshirts = [{
    id: 93,
    item_img: "./imgs/sweatshirt1/1.webp",
    item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
    price: 1199,
},
{
    id: 94,
    item_img: "./imgs/sweatshirt1/2.webp",
    item_name: "SUPIMA Sweatshirt - Be The Change",
    price: 1899,
},
{
    id: 95,
    item_img: "./imgs/sweatshirt1/3.webp",
    item_name: "Oversized Sweatshirt - Be The Change",
    price: 1099,
},
{
    id: 96,
    item_img: "./imgs/sweatshirt1/4.webp",
    item_name: "Oversized SUPIMA Sweatshirt",
    price: 999,
},
{
    id: 97,
    item_img: "./imgs/sweatshirt1/5.webp",
    item_name: "SUPIMA Sweatshirt - Be The Change",
    price: 1199,
},
{
    id: 98,
    item_img: "./imgs/sweatshirt1/6.webp",
    item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
    price: 1399,
},
{
    id: 99,
    item_img: "./imgs/sweatshirt1/7.webp",
    item_name: "Regular Fit Navy Blue Pique Sweatshirt",
    price: 899,
},
{
    id: 100,
    item_img: "./imgs/sweatshirt1/8.webp",
    item_name: "Fit Navy Blue Pique Sweatshirt",
    price: 799,
}]

const femaleSweatshirts = [{
    id: 101,
    item_img: "./imgs/sweatshirt2/1.webp",
    item_name: "Oversized SUPIMA Sweatshirt - Be The Change",
    price: 1199,
},
{
    id: 102,
    item_img: "./imgs/sweatshirt2/2.webp",
    item_name: "SUPIMA Sweatshirt - Be The Change",
    price: 1899,
},
{
    id: 103,
    item_img: "./imgs/sweatshirt2/3.webp",
    item_name: "Oversized Sweatshirt - Be The Change",
    price: 1099,
},
{
    id: 104,
    item_img: "./imgs/sweatshirt2/4.webp",
    item_name: "Oversized SUPIMA Sweatshirt",
    price: 999,
},
{
    id: 105,
    item_img: "./imgs/sweatshirt2/5.webp",
    item_name: "SUPIMA Sweatshirt - Be The Change",
    price: 1199,
},
{
    id: 106,
    item_img: "./imgs/sweatshirt2/6.webp",
    item_name: "Textured Regular Fit Navy Blue Pique Sweatshirt",
    price: 1399,
},
{
    id: 107,
    item_img: "./imgs/sweatshirt2/7.webp",
    item_name: "Regular Fit Navy Blue Pique Sweatshirt",
    price: 899,
}
]

const tShirts = [{
    id: 108,
    item_img: "./imgs/tshirt/1.webp",
    item_name: "Oversized SUPIMA T-shirt - Be The Change",
    price: 1199,
},
{
    id: 109,
    item_img: "./imgs/tshirt/2.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1899,
},
{
    id: 110,
    item_img: "./imgs/tshirt/3.webp",
    item_name: "Oversized T-shirt - Be The Change",
    price: 1099,
},
{
    id: 111,
    item_img: "./imgs/tshirt/4.webp",
    item_name: "Oversized SUPIMA T-shirt",
    price: 999,
},
{
    id: 112,
    item_img: "./imgs/tshirt/5.webp",
    item_name: "SUPIMA T-shirt - Be The Change",
    price: 1199,
},
{
    id: 113,
    item_img: "./imgs/tshirt/6.webp",
    item_name: "Textured Regular Fit Navy Blue Pique T-shirt",
    price: 1399,
},
{
    id: 114,
    item_img: "./imgs/tshirt/7.webp",
    item_name: "Regular Fit Navy Blue Pique T-shirt",
    price: 1299,
},
{
    id: 115,
    item_img: "./imgs/tshirt/8.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 999,
},
{
    id: 116,
    item_img: "./imgs/tshirt/9.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 799,
},
{
    id: 117,
    item_img: "./imgs/tshirt/10.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 1099,
},
{
    id: 118,
    item_img: "./imgs/tshirt/12.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 1199,
},
{
    id: 119,
    item_img: "./imgs/tshirt/12.webp",
    item_name: "Fit Navy Blue Pique T-shirt",
    price: 1399,
}]  